version: '2'
services:
  elastic:
    image: elasticsearch:5.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    command: [elasticsearch, -Enetwork.host=0.0.0.0, -Enetwork.bind_host=0.0.0.0, -Ecluster.name=elasticlaster]
  kibana:
    image: kibana:5.1.1
    links:
      - elastic:elasticsearch
    ports:
      - "5601:5601"
    depends_on:
      - elastic
  dockermon:
    image: boriska70/dockermon
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - elastic
    depends_on:
      - elastic
    command: "/usr/bin/dockermon -esurl=http://elastic:9200 -cci=300"
